import type { Exercise } from './types'

export const exercises: Exercise[] = [
  {
    id: 'barbellBenchPress',
    slug: 'barbell-bench-press',
    equipmentIds: ['barbell', 'bench', 'rack'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii'],
    measurementType: 'weightReps',
    aliases: ['bench press', 'bb bench press', 'flat barbell bench press'],
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/BBBenchPress'],
  },
  {
    id: 'dumbbellBenchPress',
    slug: 'dumbbell-bench-press',
    equipmentIds: ['dumbbell', 'bench'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii', 'bicepsBrachii'],
    measurementType: 'weightReps',
    aliases: ['db bench press', 'flat dumbbell press'],
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/DBBenchPress'],
  },
  {
    id: 'inclineBarbellBenchPress',
    slug: 'incline-barbell-bench-press',
    equipmentIds: ['barbell', 'bench', 'rack'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii'],
    measurementType: 'weightReps',
    aliases: ['barbell incline bench press', 'incline press', 'upper chest press'],
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralClavicular/BBInclineBenchPress'],
  },
  {
    id: 'inclineDumbbellBenchPress',
    slug: 'incline-dumbbell-bench-press',
    equipmentIds: ['dumbbell', 'bench'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii', 'bicepsBrachii'],
    measurementType: 'weightReps',
    aliases: ['incline db bench press', 'incline dumbbell press', 'upper chest dumbbell press'],
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralClavicular/DBInclineBenchPress'],
  },
  {
    id: 'declineBarbellBenchPress',
    slug: 'decline-barbell-bench-press',
    equipmentIds: ['barbell', 'bench', 'rack'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii'],
    measurementType: 'weightReps',
    aliases: ['decline bench press', 'decline press'],
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/BBDeclineBenchPress'],
  },
  {
    id: 'declineDumbbellBenchPress',
    slug: 'decline-dumbbell-bench-press',
    equipmentIds: ['dumbbell', 'bench'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii', 'bicepsBrachii'],
    measurementType: 'weightReps',
    aliases: ['decline db bench press', 'decline dumbbell press'],
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/DBDeclineBenchPress'],
  },
  {
    id: 'pecDeck',
    slug: 'pec-deck',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['pectoralisMinor', 'bicepsBrachii'],
    measurementType: 'weightReps',
    aliases: ['pec fly', 'machine fly'],
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/LVPecDeckFly'],
  },
  {
    id: 'cableFly',
    slug: 'cable-fly',
    equipmentIds: ['cableMachine'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['pectoralisMinor', 'bicepsBrachii'],
    measurementType: 'weightReps',
    aliases: ['cable chest fly', 'standing cable fly'],
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/CBStandingFly'],
  },
  {
    id: 'dip',
    slug: 'dip',
    equipmentIds: ['bodyweight', 'dipBars'],
    primaryMuscleIds: ['pectoralisMajor', 'tricepsBrachii'],
    secondaryMuscleIds: ['deltoidAnterior', 'latissimusDorsi'],
    measurementType: 'reps',
    aliases: ['chest dip', 'parallel bar dip', 'bodyweight dip'],
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/BWChestDip'],
  },
  {
    id: 'pushUp',
    slug: 'push-up',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii', 'rectusAbdominis', 'obliques'],
    measurementType: 'reps',
    aliases: ['pushup', 'press up'],
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/BWPushup'],
  },
  {
    id: 'weightedPushUp',
    slug: 'weighted-push-up',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii', 'rectusAbdominis', 'obliques'],
    measurementType: 'weightReps',
    aliases: ['weighted pushup', 'weighted press up'],
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/WtPushup'],
  },
  {
    id: 'pullUp',
    slug: 'pull-up',
    equipmentIds: ['bodyweight', 'pullUpBar'],
    primaryMuscleIds: ['latissimusDorsi'],
    secondaryMuscleIds: ['bicepsBrachii', 'brachialis', 'brachioradialis', 'rhomboids', 'trapezius', 'deltoidPosterior'],
    measurementType: 'reps',
    aliases: ['wide grip pull up', 'bodyweight pull up'],
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/WtPullup'],
  },
  {
    id: 'wideGripPullUp',
    slug: 'wide-grip-pull-up',
    equipmentIds: ['bodyweight', 'pullUpBar'],
    primaryMuscleIds: ['latissimusDorsi'],
    secondaryMuscleIds: ['bicepsBrachii', 'brachialis', 'brachioradialis', 'rhomboids', 'trapezius', 'deltoidPosterior'],
    measurementType: 'reps',
    aliases: ['wide grip pull up', 'wide pull up'],
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/WtPullup'],
  },
  {
    id: 'chinUp',
    slug: 'chin-up',
    equipmentIds: ['bodyweight', 'pullUpBar'],
    primaryMuscleIds: ['latissimusDorsi', 'bicepsBrachii'],
    secondaryMuscleIds: ['brachialis', 'brachioradialis', 'rhomboids', 'trapezius', 'deltoidPosterior'],
    measurementType: 'reps',
    aliases: ['chin up', 'underhand pull up'],
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/WtUnderhandChinup'],
  },
  {
    id: 'latPulldown',
    slug: 'lat-pulldown',
    equipmentIds: ['cableMachine', 'machine'],
    primaryMuscleIds: ['latissimusDorsi'],
    secondaryMuscleIds: ['bicepsBrachii', 'brachialis', 'brachioradialis', 'rhomboids', 'trapezius', 'deltoidPosterior'],
    measurementType: 'weightReps',
    aliases: ['front pulldown', 'cable pulldown', 'wide grip lat pulldown'],
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/CBFrontPulldown'],
  },
  {
    id: 'closeGripLatPulldown',
    slug: 'close-grip-lat-pulldown',
    equipmentIds: ['cableMachine', 'machine'],
    primaryMuscleIds: ['latissimusDorsi'],
    secondaryMuscleIds: ['bicepsBrachii', 'brachialis', 'brachioradialis', 'rhomboids', 'trapezius', 'deltoidPosterior'],
    measurementType: 'weightReps',
    aliases: ['close grip pulldown', 'close grip cable pulldown'],
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/CBCloseGripPulldown'],
  },
  {
    id: 'barbellRow',
    slug: 'barbell-row',
    equipmentIds: ['barbell'],
    primaryMuscleIds: ['latissimusDorsi', 'rhomboids', 'trapezius'],
    secondaryMuscleIds: ['deltoidPosterior', 'bicepsBrachii', 'brachialis', 'brachioradialis', 'erectorSpinae', 'hamstrings', 'gluteusMaximus'],
    measurementType: 'weightReps',
    aliases: ['barbell bent over row', 'bent over row', 'pendlay row'],
    sourceUrls: ['https://exrx.net/WeightExercises/BackGeneral/BBBentOverRow'],
  },
  {
    id: 'seatedRow',
    slug: 'seated-row',
    equipmentIds: ['cableMachine', 'machine'],
    primaryMuscleIds: ['latissimusDorsi', 'rhomboids', 'trapezius'],
    secondaryMuscleIds: ['deltoidPosterior', 'bicepsBrachii', 'brachialis', 'brachioradialis', 'erectorSpinae'],
    measurementType: 'weightReps',
    aliases: ['cable seated row', 'seated row'],
    sourceUrls: ['https://exrx.net/WeightExercises/BackGeneral/CBSeatedRow'],
  },
  {
    id: 'singleArmDumbbellRow',
    slug: 'single-arm-dumbbell-row',
    equipmentIds: ['dumbbell', 'bench'],
    primaryMuscleIds: ['latissimusDorsi', 'rhomboids', 'trapezius'],
    secondaryMuscleIds: ['deltoidPosterior', 'bicepsBrachii', 'brachialis', 'brachioradialis', 'obliques'],
    measurementType: 'weightReps',
    aliases: ['single arm dumbbell row', 'one arm row', 'db row'],
    sourceUrls: ['https://exrx.net/WeightExercises/BackGeneral/DBBentOverRow'],
  },
  {
    id: 'tBarRow',
    slug: 't-bar-row',
    equipmentIds: ['barbell', 'machine'],
    primaryMuscleIds: ['latissimusDorsi', 'rhomboids', 'trapezius'],
    secondaryMuscleIds: ['deltoidPosterior', 'bicepsBrachii', 'brachialis', 'brachioradialis', 'erectorSpinae'],
    measurementType: 'weightReps',
    aliases: ['t bar row', 'landmine row'],
    sourceUrls: ['https://exrx.net/WeightExercises/BackGeneral/LVTBarRow'],
  },
  {
    id: 'straightArmPulldown',
    slug: 'straight-arm-pulldown',
    equipmentIds: ['cableMachine'],
    primaryMuscleIds: ['latissimusDorsi'],
    secondaryMuscleIds: ['pectoralisMajor', 'tricepsBrachii'],
    measurementType: 'weightReps',
    aliases: ['straight arm pulldown', 'cable straight arm pulldown'],
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/CBStraightArmPulldown'],
  },
  {
    id: 'deadlift',
    slug: 'deadlift',
    equipmentIds: ['barbell'],
    primaryMuscleIds: ['gluteusMaximus', 'erectorSpinae', 'quadriceps'],
    secondaryMuscleIds: ['hamstrings', 'trapezius', 'latissimusDorsi', 'rectusAbdominis', 'obliques'],
    measurementType: 'weightReps',
    aliases: ['barbell deadlift', 'conventional deadlift'],
    sourceUrls: ['https://exrx.net/WeightExercises/ErectorSpinae/BBDeadlift'],
  },
  {
    id: 'romanianDeadlift',
    slug: 'romanian-deadlift',
    equipmentIds: ['barbell'],
    primaryMuscleIds: ['hamstrings', 'gluteusMaximus'],
    secondaryMuscleIds: ['erectorSpinae', 'trapezius', 'gastrocnemius'],
    measurementType: 'weightReps',
    aliases: ['rdl', 'barbell romanian deadlift'],
    sourceUrls: ['https://exrx.net/WeightExercises/OlympicLifts/RomanianDeadlift'],
  },
  {
    id: 'sumoDeadlift',
    slug: 'sumo-deadlift',
    equipmentIds: ['barbell'],
    primaryMuscleIds: ['gluteusMaximus', 'quadriceps', 'erectorSpinae'],
    secondaryMuscleIds: ['hamstrings', 'hipAdductors', 'trapezius', 'latissimusDorsi', 'rectusAbdominis', 'obliques'],
    measurementType: 'weightReps',
    aliases: ['sumo deadlift', 'wide stance deadlift'],
    sourceUrls: ['https://exrx.net/WeightExercises/ErectorSpinae/BBSumoDeadlift'],
  },
  {
    id: 'barbellSquat',
    slug: 'barbell-squat',
    equipmentIds: ['barbell', 'rack'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['gluteusMaximus', 'hamstrings', 'hipAdductors', 'erectorSpinae', 'rectusAbdominis', 'obliques'],
    measurementType: 'weightReps',
    aliases: ['back squat', 'barbell squat', 'squat'],
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BBSquat'],
  },
  {
    id: 'squat',
    slug: 'squat',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['gluteusMaximus', 'hamstrings', 'hipAdductors', 'erectorSpinae', 'rectusAbdominis', 'obliques'],
    measurementType: 'reps',
    aliases: ['bodyweight squat', 'air squat'],
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BWSquat'],
  },
  {
    id: 'frontSquat',
    slug: 'front-squat',
    equipmentIds: ['barbell', 'rack'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['gluteusMaximus', 'hamstrings', 'hipAdductors', 'erectorSpinae', 'rectusAbdominis', 'obliques'],
    measurementType: 'weightReps',
    aliases: ['barbell front squat'],
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BBFrontSquat'],
  },
  {
    id: 'legPress',
    slug: 'leg-press',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['gluteusMaximus', 'hamstrings', 'hipAdductors', 'gastrocnemius', 'soleus'],
    measurementType: 'weightReps',
    aliases: ['45 degree leg press', 'machine leg press'],
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LV45LegPress'],
  },
  {
    id: 'legPressMachine',
    slug: 'leg-press-machine',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['gluteusMaximus', 'hamstrings', 'hipAdductors', 'gastrocnemius', 'soleus'],
    measurementType: 'weightReps',
    aliases: ['machine leg press', 'leg press'],
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LV45LegPress'],
  },
  {
    id: 'hackSquat',
    slug: 'hack-squat',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['gluteusMaximus', 'hamstrings', 'hipAdductors', 'gastrocnemius', 'soleus'],
    measurementType: 'weightReps',
    aliases: ['machine hack squat'],
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LVHackSquat'],
  },
  {
    id: 'gluteBridge',
    slug: 'glute-bridge',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['gluteusMaximus'],
    secondaryMuscleIds: ['hamstrings', 'rectusAbdominis', 'obliques'],
    measurementType: 'reps',
    aliases: ['bodyweight glute bridge', 'floor bridge'],
    sourceUrls: ['https://exrx.net/WeightExercises/GluteusMaximus/BWGluteBridge'],
  },
  {
    id: 'barbellHipThrust',
    slug: 'barbell-hip-thrust',
    equipmentIds: ['barbell', 'bench'],
    primaryMuscleIds: ['gluteusMaximus'],
    secondaryMuscleIds: ['hamstrings', 'quadriceps', 'erectorSpinae', 'rectusAbdominis', 'obliques'],
    measurementType: 'weightReps',
    aliases: ['barbell hip thrust'],
    sourceUrls: ['https://exrx.net/WeightExercises/GluteusMaximus/BBHipThrust'],
  },
  {
    id: 'lunge',
    slug: 'lunge',
    equipmentIds: ['bodyweight', 'barbell', 'dumbbell'],
    primaryMuscleIds: ['quadriceps', 'gluteusMaximus'],
    secondaryMuscleIds: ['hamstrings', 'hipAdductors', 'gastrocnemius', 'gluteusMedius'],
    measurementType: 'weightReps',
    aliases: ['forward lunge', 'barbell lunge', 'dumbbell lunge'],
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BBLunge'],
  },
  {
    id: 'bulgarianSplitSquat',
    slug: 'bulgarian-split-squat',
    equipmentIds: ['bodyweight', 'dumbbell', 'bench'],
    primaryMuscleIds: ['quadriceps', 'gluteusMaximus'],
    secondaryMuscleIds: ['hamstrings', 'hipAdductors', 'gastrocnemius', 'gluteusMedius'],
    measurementType: 'weightReps',
    aliases: ['split squat', 'rear foot elevated split squat'],
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/DBSingleLegSplitSquat'],
  },
  {
    id: 'walkingLunge',
    slug: 'walking-lunge',
    equipmentIds: ['bodyweight', 'barbell', 'dumbbell'],
    primaryMuscleIds: ['quadriceps', 'gluteusMaximus'],
    secondaryMuscleIds: ['hamstrings', 'hipAdductors', 'gastrocnemius', 'gluteusMedius'],
    measurementType: 'weightDistance',
    aliases: ['walking lunge', 'dumbbell walking lunge'],
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/DBWalkingLunge'],
  },
  {
    id: 'legExtension',
    slug: 'leg-extension',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: [],
    measurementType: 'weightReps',
    aliases: ['machine leg extension', 'knee extension'],
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LVLegExtension'],
  },
  {
    id: 'legCurl',
    slug: 'leg-curl',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['hamstrings'],
    secondaryMuscleIds: ['gastrocnemius'],
    measurementType: 'weightReps',
    aliases: ['lying leg curl', 'hamstring curl', 'machine leg curl'],
    sourceUrls: ['https://exrx.net/WeightExercises/Hamstrings/LVLyingLegCurl'],
  },
  {
    id: 'standingCalfRaise',
    slug: 'standing-calf-raise',
    equipmentIds: ['machine', 'bodyweight'],
    primaryMuscleIds: ['gastrocnemius'],
    secondaryMuscleIds: ['soleus'],
    measurementType: 'weightReps',
    aliases: ['calf raise', 'standing calf raise'],
    sourceUrls: ['https://exrx.net/WeightExercises/Gastrocnemius/LVStandingCalfRaise'],
  },
  {
    id: 'seatedCalfRaise',
    slug: 'seated-calf-raise',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['soleus'],
    secondaryMuscleIds: ['gastrocnemius'],
    measurementType: 'weightReps',
    aliases: ['seated calf raise'],
    sourceUrls: ['https://exrx.net/WeightExercises/Soleus/LVSeatedCalfRaise'],
  },
  {
    id: 'hipAbduction',
    slug: 'hip-abduction',
    equipmentIds: ['machine', 'resistanceBand'],
    primaryMuscleIds: ['gluteusMedius'],
    secondaryMuscleIds: ['gluteusMaximus'],
    measurementType: 'weightReps',
    aliases: ['hip abductor', 'machine hip abduction'],
    sourceUrls: ['https://exrx.net/WeightExercises/HipAbductor/LVSeatedHipAbduction'],
  },
  {
    id: 'hipAdduction',
    slug: 'hip-adduction',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['hipAdductors'],
    secondaryMuscleIds: [],
    measurementType: 'weightReps',
    aliases: ['hip adductor', 'machine hip adduction'],
    sourceUrls: ['https://exrx.net/WeightExercises/HipAdductors/LVSeatedHipAdduction'],
  },
  {
    id: 'barbellOverheadPress',
    slug: 'barbell-overhead-press',
    equipmentIds: ['barbell', 'rack'],
    primaryMuscleIds: ['deltoidAnterior'],
    secondaryMuscleIds: ['deltoidLateral', 'tricepsBrachii', 'trapezius', 'serratusAnterior', 'pectoralisMajor'],
    measurementType: 'weightReps',
    aliases: ['barbell overhead press', 'military press', 'strict press'],
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/BBMilitaryPress'],
  },
  {
    id: 'dumbbellShoulderPress',
    slug: 'dumbbell-shoulder-press',
    equipmentIds: ['dumbbell', 'bench'],
    primaryMuscleIds: ['deltoidAnterior'],
    secondaryMuscleIds: ['deltoidLateral', 'tricepsBrachii', 'trapezius', 'serratusAnterior'],
    measurementType: 'weightReps',
    aliases: ['db shoulder press', 'dumbbell overhead press'],
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/DBShoulderPress'],
  },
  {
    id: 'arnoldPress',
    slug: 'arnold-press',
    equipmentIds: ['dumbbell', 'bench'],
    primaryMuscleIds: ['deltoidAnterior'],
    secondaryMuscleIds: ['deltoidLateral', 'tricepsBrachii', 'trapezius', 'serratusAnterior'],
    measurementType: 'weightReps',
    aliases: ['arnold dumbbell press', 'arnold shoulder press'],
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/DBArnoldPress'],
  },
  {
    id: 'dumbbellLateralRaise',
    slug: 'dumbbell-lateral-raise',
    equipmentIds: ['dumbbell', 'cableMachine'],
    primaryMuscleIds: ['deltoidLateral'],
    secondaryMuscleIds: ['deltoidAnterior', 'trapezius', 'serratusAnterior'],
    measurementType: 'weightReps',
    aliases: ['dumbbell lateral raise', 'side lateral raise', 'side raise'],
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidLateral/DBLateralRaise'],
  },
  {
    id: 'dumbbellFrontRaise',
    slug: 'dumbbell-front-raise',
    equipmentIds: ['dumbbell'],
    primaryMuscleIds: ['deltoidAnterior'],
    secondaryMuscleIds: ['deltoidLateral', 'serratusAnterior', 'trapezius'],
    measurementType: 'weightReps',
    aliases: ['front raise', 'dumbbell front raise'],
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/DBFrontRaise'],
  },
  {
    id: 'facePull',
    slug: 'face-pull',
    equipmentIds: ['cableMachine', 'resistanceBand'],
    primaryMuscleIds: ['deltoidPosterior'],
    secondaryMuscleIds: ['rhomboids', 'trapezius', 'brachialis', 'brachioradialis', 'bicepsBrachii'],
    measurementType: 'weightReps',
    aliases: ['cable face pull', 'rope face pull', 'rear delt row'],
    sourceUrls: [
      'https://exrx.net/WeightExercises/DeltoidPosterior/CBRearDeltRow',
      'https://www.healthline.com/health/face-pulls',
    ],
  },
  {
    id: 'reverseFly',
    slug: 'reverse-fly',
    equipmentIds: ['dumbbell', 'machine', 'cableMachine'],
    primaryMuscleIds: ['deltoidPosterior'],
    secondaryMuscleIds: ['rhomboids', 'trapezius'],
    measurementType: 'weightReps',
    aliases: ['reverse flye', 'rear delt fly'],
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidPosterior/DBRearLateralRaise'],
  },
  {
    id: 'shrug',
    slug: 'shrug',
    equipmentIds: ['barbell', 'dumbbell', 'machine'],
    primaryMuscleIds: ['trapezius'],
    secondaryMuscleIds: ['levatorScapulae'],
    measurementType: 'weightReps',
    aliases: ['barbell shrug', 'dumbbell shrug'],
    sourceUrls: ['https://exrx.net/WeightExercises/TrapeziusUpper/BBShrug'],
  },
  {
    id: 'barbellCurl',
    slug: 'barbell-curl',
    equipmentIds: ['barbell'],
    primaryMuscleIds: ['bicepsBrachii'],
    secondaryMuscleIds: ['brachialis', 'brachioradialis'],
    measurementType: 'weightReps',
    aliases: ['bb curl', 'standing barbell curl'],
    sourceUrls: ['https://exrx.net/WeightExercises/Biceps/BBCurl'],
  },
  {
    id: 'dumbbellCurl',
    slug: 'dumbbell-curl',
    equipmentIds: ['dumbbell'],
    primaryMuscleIds: ['bicepsBrachii'],
    secondaryMuscleIds: ['brachialis', 'brachioradialis'],
    measurementType: 'weightReps',
    aliases: ['db curl', 'alternating dumbbell curl'],
    sourceUrls: ['https://exrx.net/WeightExercises/Biceps/DBCurl'],
  },
  {
    id: 'hammerCurl',
    slug: 'hammer-curl',
    equipmentIds: ['dumbbell'],
    primaryMuscleIds: ['brachioradialis'],
    secondaryMuscleIds: ['brachialis', 'bicepsBrachii'],
    measurementType: 'weightReps',
    aliases: ['dumbbell hammer curl', 'neutral grip curl'],
    sourceUrls: ['https://exrx.net/WeightExercises/Brachioradialis/DBHammerCurl'],
  },
  {
    id: 'preacherCurl',
    slug: 'preacher-curl',
    equipmentIds: ['barbell', 'dumbbell', 'bench'],
    primaryMuscleIds: ['bicepsBrachii'],
    secondaryMuscleIds: ['brachialis', 'brachioradialis'],
    measurementType: 'weightReps',
    aliases: ['preacher curl', 'preacher bench curl'],
    sourceUrls: ['https://exrx.net/WeightExercises/Biceps/BBPreacherCurl'],
  },
  {
    id: 'concentrationCurl',
    slug: 'concentration-curl',
    equipmentIds: ['dumbbell'],
    primaryMuscleIds: ['bicepsBrachii'],
    secondaryMuscleIds: ['brachialis', 'brachioradialis'],
    measurementType: 'weightReps',
    aliases: ['concentration curl', 'seated concentration curl'],
    sourceUrls: ['https://exrx.net/WeightExercises/Biceps/DBConcentrationCurl'],
  },
  {
    id: 'tricepsPushdown',
    slug: 'triceps-pushdown',
    equipmentIds: ['cableMachine'],
    primaryMuscleIds: ['tricepsBrachii'],
    secondaryMuscleIds: ['latissimusDorsi', 'rectusAbdominis', 'obliques'],
    measurementType: 'weightReps',
    aliases: ['cable pushdown', 'tricep pushdown', 'rope pushdown'],
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/CBPushdown'],
  },
  {
    id: 'closeGripBenchPress',
    slug: 'close-grip-bench-press',
    equipmentIds: ['barbell', 'bench', 'rack'],
    primaryMuscleIds: ['tricepsBrachii'],
    secondaryMuscleIds: ['pectoralisMajor', 'deltoidAnterior'],
    measurementType: 'weightReps',
    aliases: ['close grip bench press', 'close grip press'],
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/BBCloseGripBenchPress'],
  },
  {
    id: 'overheadTricepsExtension',
    slug: 'overhead-triceps-extension',
    equipmentIds: ['dumbbell', 'cableMachine'],
    primaryMuscleIds: ['tricepsBrachii'],
    secondaryMuscleIds: [],
    measurementType: 'weightReps',
    aliases: ['triceps extension', 'overhead extension'],
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/DBTriExt'],
  },
  {
    id: 'skullCrusher',
    slug: 'skull-crusher',
    equipmentIds: ['barbell', 'dumbbell', 'bench'],
    primaryMuscleIds: ['tricepsBrachii'],
    secondaryMuscleIds: [],
    measurementType: 'weightReps',
    aliases: ['lying triceps extension', 'skull crusher'],
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/BBLyingTriExt'],
  },
  {
    id: 'tricepsRopeExtension',
    slug: 'triceps-rope-extension',
    equipmentIds: ['cableMachine'],
    primaryMuscleIds: ['tricepsBrachii'],
    secondaryMuscleIds: [],
    measurementType: 'weightReps',
    aliases: ['rope extension', 'rope pushdown'],
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/CBPushdown'],
  },
  {
    id: 'crunch',
    slug: 'crunch',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['rectusAbdominis'],
    secondaryMuscleIds: ['obliques'],
    measurementType: 'reps',
    aliases: ['ab crunch', 'floor crunch'],
    sourceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/BWCrunch'],
  },
  {
    id: 'plank',
    slug: 'plank',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['rectusAbdominis', 'transverseAbdominis'],
    secondaryMuscleIds: ['obliques', 'quadriceps', 'pectoralisMajor', 'serratusAnterior'],
    measurementType: 'duration',
    aliases: ['front plank', 'forearm plank'],
    sourceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/BWFrontPlank'],
  },
  {
    id: 'hangingLegRaise',
    slug: 'hanging-leg-raise',
    equipmentIds: ['bodyweight', 'pullUpBar'],
    primaryMuscleIds: ['rectusAbdominis', 'iliopsoas'],
    secondaryMuscleIds: ['obliques', 'quadriceps'],
    measurementType: 'reps',
    aliases: ['hanging knee raise', 'hanging leg hip raise', 'leg raise'],
    sourceUrls: [
      'https://exrx.net/WeightExercises/RectusAbdominis/BWHangingLegHipRaiseAbStrap',
      'https://exrx.net/WeightExercises/HipFlexors/WtHangLegRaise',
    ],
  },
  {
    id: 'russianTwist',
    slug: 'russian-twist',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['obliques'],
    secondaryMuscleIds: ['rectusAbdominis', 'iliopsoas'],
    measurementType: 'reps',
    aliases: ['russian twist', 'seated twist'],
    sourceUrls: ['https://exrx.net/WeightExercises/Obliques/WtRussianTwist'],
  },
  {
    id: 'sitUp',
    slug: 'sit-up',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['rectusAbdominis'],
    secondaryMuscleIds: ['obliques', 'iliopsoas'],
    measurementType: 'reps',
    aliases: ['sit up', 'curl up'],
    sourceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/BWSitUp'],
  },
  {
    id: 'cableCrunch',
    slug: 'cable-crunch',
    equipmentIds: ['cableMachine'],
    primaryMuscleIds: ['rectusAbdominis'],
    secondaryMuscleIds: ['obliques'],
    measurementType: 'weightReps',
    aliases: ['cable crunch', 'kneeling cable crunch'],
    sourceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/CBKneelingCrunch'],
  },
  {
    id: 'deadBug',
    slug: 'dead-bug',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['transverseAbdominis'],
    secondaryMuscleIds: ['rectusAbdominis', 'obliques', 'iliopsoas'],
    measurementType: 'reps',
    aliases: ['dead bug', 'deadbug'],
    sourceUrls: [],
  },
  {
    id: 'birdDog',
    slug: 'bird-dog',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['erectorSpinae', 'gluteusMaximus'],
    secondaryMuscleIds: ['rectusAbdominis', 'obliques', 'deltoidPosterior'],
    measurementType: 'reps',
    aliases: ['bird dog', 'quadruped opposite arm leg raise'],
    sourceUrls: [],
  },
]
