import type { Exercise } from './types'

export const exercises: Exercise[] = [
  {
    id: 'barbellBenchPress',
    slug: 'barbell-bench-press',
    equipmentIds: ['barbell', 'bench', 'rack'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/BBBenchPress'],
  },
  {
    id: 'dumbbellBenchPress',
    slug: 'dumbbell-bench-press',
    equipmentIds: ['dumbbell', 'bench'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii', 'bicepsBrachii'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/DBBenchPress'],
  },
  {
    id: 'inclineBarbellBenchPress',
    slug: 'incline-barbell-bench-press',
    equipmentIds: ['barbell', 'bench', 'rack'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralClavicular/BBInclineBenchPress'],
  },
  {
    id: 'inclineDumbbellBenchPress',
    slug: 'incline-dumbbell-bench-press',
    equipmentIds: ['dumbbell', 'bench'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii', 'bicepsBrachii'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralClavicular/DBInclineBenchPress'],
  },
  {
    id: 'declineBarbellBenchPress',
    slug: 'decline-barbell-bench-press',
    equipmentIds: ['barbell', 'bench', 'rack'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/BBDeclineBenchPress'],
  },
  {
    id: 'declineDumbbellBenchPress',
    slug: 'decline-dumbbell-bench-press',
    equipmentIds: ['dumbbell', 'bench'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii', 'bicepsBrachii'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/DBDeclineBenchPress'],
  },
  {
    id: 'pecDeck',
    slug: 'pec-deck',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['pectoralisMinor', 'bicepsBrachii'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/LVPecDeckFly'],
  },
  {
    id: 'cableFly',
    slug: 'cable-fly',
    equipmentIds: ['cableMachine'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['pectoralisMinor', 'bicepsBrachii'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/CBStandingFly'],
  },
  {
    id: 'dip',
    slug: 'dip',
    equipmentIds: ['bodyweight', 'dipBars'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['tricepsBrachii', 'deltoidAnterior'],
    movementPattern: 'push',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/BWChestDip'],
  },
  {
    id: 'pushUp',
    slug: 'push-up',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii', 'rectusAbdominis', 'obliques'],
    movementPattern: 'push',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/BWPushup'],
  },
  {
    id: 'weightedPushUp',
    slug: 'weighted-push-up',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['pectoralisMajor'],
    secondaryMuscleIds: ['deltoidAnterior', 'tricepsBrachii', 'rectusAbdominis', 'obliques'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/WtPushup'],
  },
  {
    id: 'pullUp',
    slug: 'pull-up',
    equipmentIds: ['bodyweight', 'pullUpBar'],
    primaryMuscleIds: ['latissimusDorsi'],
    secondaryMuscleIds: ['bicepsBrachii', 'brachialis', 'brachioradialis', 'rhomboids', 'trapezius', 'deltoidPosterior'],
    movementPattern: 'pull',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/WtPullup'],
  },
  {
    id: 'wideGripPullUp',
    slug: 'wide-grip-pull-up',
    equipmentIds: ['bodyweight', 'pullUpBar'],
    primaryMuscleIds: ['latissimusDorsi'],
    secondaryMuscleIds: ['bicepsBrachii', 'brachialis', 'brachioradialis', 'rhomboids', 'trapezius', 'deltoidPosterior'],
    movementPattern: 'pull',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/WtPullup'],
  },
  {
    id: 'chinUp',
    slug: 'chin-up',
    equipmentIds: ['bodyweight', 'pullUpBar'],
    primaryMuscleIds: ['latissimusDorsi', 'bicepsBrachii'],
    secondaryMuscleIds: ['brachialis', 'brachioradialis', 'rhomboids', 'trapezius', 'deltoidPosterior'],
    movementPattern: 'pull',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/WtUnderhandChinup'],
  },
  {
    id: 'latPulldown',
    slug: 'lat-pulldown',
    equipmentIds: ['cableMachine', 'machine'],
    primaryMuscleIds: ['latissimusDorsi'],
    secondaryMuscleIds: ['bicepsBrachii', 'brachialis', 'brachioradialis', 'rhomboids', 'trapezius', 'deltoidPosterior'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/CBFrontPulldown'],
  },
  {
    id: 'closeGripLatPulldown',
    slug: 'close-grip-lat-pulldown',
    equipmentIds: ['cableMachine', 'machine'],
    primaryMuscleIds: ['latissimusDorsi'],
    secondaryMuscleIds: ['bicepsBrachii', 'brachialis', 'brachioradialis', 'rhomboids', 'trapezius', 'deltoidPosterior'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/CBCloseGripPulldown'],
  },
  {
    id: 'barbellRow',
    slug: 'barbell-row',
    equipmentIds: ['barbell'],
    primaryMuscleIds: ['latissimusDorsi', 'rhomboids', 'trapezius'],
    secondaryMuscleIds: ['deltoidPosterior', 'bicepsBrachii', 'brachialis', 'brachioradialis', 'erectorSpinae', 'hamstrings', 'gluteusMaximus'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/BackGeneral/BBBentOverRow'],
  },
  {
    id: 'seatedRow',
    slug: 'seated-row',
    equipmentIds: ['cableMachine', 'machine'],
    primaryMuscleIds: ['latissimusDorsi', 'rhomboids', 'trapezius'],
    secondaryMuscleIds: ['deltoidPosterior', 'bicepsBrachii', 'brachialis', 'brachioradialis', 'erectorSpinae'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/BackGeneral/CBSeatedRow'],
  },
  {
    id: 'singleArmDumbbellRow',
    slug: 'single-arm-dumbbell-row',
    equipmentIds: ['dumbbell', 'bench'],
    primaryMuscleIds: ['latissimusDorsi', 'rhomboids', 'trapezius'],
    secondaryMuscleIds: ['deltoidPosterior', 'bicepsBrachii', 'brachialis', 'brachioradialis', 'obliques'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/BackGeneral/DBBentOverRow'],
  },
  {
    id: 'tBarRow',
    slug: 't-bar-row',
    equipmentIds: ['barbell', 'machine'],
    primaryMuscleIds: ['latissimusDorsi', 'rhomboids', 'trapezius'],
    secondaryMuscleIds: ['deltoidPosterior', 'bicepsBrachii', 'brachialis', 'brachioradialis', 'erectorSpinae'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/BackGeneral/LVTBarRow'],
  },
  {
    id: 'straightArmPulldown',
    slug: 'straight-arm-pulldown',
    equipmentIds: ['cableMachine'],
    primaryMuscleIds: ['latissimusDorsi'],
    secondaryMuscleIds: ['pectoralisMajor', 'tricepsBrachii'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/CBStraightArmPulldown'],
  },
  {
    id: 'deadlift',
    slug: 'deadlift',
    equipmentIds: ['barbell'],
    primaryMuscleIds: ['gluteusMaximus', 'erectorSpinae', 'quadriceps'],
    secondaryMuscleIds: ['hamstrings', 'trapezius', 'latissimusDorsi', 'rectusAbdominis', 'obliques'],
    movementPattern: 'fullBody',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/ErectorSpinae/BBDeadlift'],
  },
  {
    id: 'romanianDeadlift',
    slug: 'romanian-deadlift',
    equipmentIds: ['barbell'],
    primaryMuscleIds: ['hamstrings', 'gluteusMaximus', 'erectorSpinae'],
    secondaryMuscleIds: ['trapezius', 'gastrocnemius', 'rectusAbdominis', 'obliques'],
    movementPattern: 'fullBody',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/OlympicLifts/RomanianDeadlift'],
  },
  {
    id: 'sumoDeadlift',
    slug: 'sumo-deadlift',
    equipmentIds: ['barbell'],
    primaryMuscleIds: ['gluteusMaximus', 'quadriceps', 'erectorSpinae'],
    secondaryMuscleIds: ['hamstrings', 'hipAdductors', 'trapezius', 'latissimusDorsi', 'rectusAbdominis', 'obliques'],
    movementPattern: 'fullBody',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/ErectorSpinae/BBSumoDeadlift'],
  },
  {
    id: 'barbellSquat',
    slug: 'barbell-squat',
    equipmentIds: ['barbell', 'rack'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['gluteusMaximus', 'hamstrings', 'hipAdductors', 'erectorSpinae', 'rectusAbdominis', 'obliques'],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BBSquat'],
  },
  {
    id: 'squat',
    slug: 'squat',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['gluteusMaximus', 'hamstrings', 'hipAdductors', 'erectorSpinae', 'rectusAbdominis', 'obliques'],
    movementPattern: 'legs',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BWSquat'],
  },
  {
    id: 'frontSquat',
    slug: 'front-squat',
    equipmentIds: ['barbell', 'rack'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['gluteusMaximus', 'hamstrings', 'hipAdductors', 'erectorSpinae', 'rectusAbdominis', 'obliques'],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BBFrontSquat'],
  },
  {
    id: 'legPress',
    slug: 'leg-press',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['gluteusMaximus', 'hamstrings', 'hipAdductors', 'gastrocnemius', 'soleus'],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LV45LegPress'],
  },
  {
    id: 'legPressMachine',
    slug: 'leg-press-machine',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['gluteusMaximus', 'hamstrings', 'hipAdductors', 'gastrocnemius', 'soleus'],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LV45LegPress'],
  },
  {
    id: 'hackSquat',
    slug: 'hack-squat',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: ['gluteusMaximus', 'hamstrings', 'hipAdductors', 'gastrocnemius', 'soleus'],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LVHackSquat'],
  },
  {
    id: 'gluteBridge',
    slug: 'glute-bridge',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['gluteusMaximus'],
    secondaryMuscleIds: ['hamstrings', 'rectusAbdominis', 'obliques'],
    movementPattern: 'legs',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/GluteusMaximus/BWGluteBridge'],
  },
  {
    id: 'barbellHipThrust',
    slug: 'barbell-hip-thrust',
    equipmentIds: ['barbell', 'bench'],
    primaryMuscleIds: ['gluteusMaximus'],
    secondaryMuscleIds: ['hamstrings', 'quadriceps', 'erectorSpinae', 'rectusAbdominis', 'obliques'],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/GluteusMaximus/BBHipThrust'],
  },
  {
    id: 'lunge',
    slug: 'lunge',
    equipmentIds: ['bodyweight', 'barbell', 'dumbbell'],
    primaryMuscleIds: ['quadriceps', 'gluteusMaximus'],
    secondaryMuscleIds: ['hamstrings', 'hipAdductors', 'gastrocnemius', 'gluteusMedius', 'rectusAbdominis', 'obliques'],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BBLunge'],
  },
  {
    id: 'bulgarianSplitSquat',
    slug: 'bulgarian-split-squat',
    equipmentIds: ['bodyweight', 'dumbbell', 'bench'],
    primaryMuscleIds: ['quadriceps', 'gluteusMaximus'],
    secondaryMuscleIds: ['hamstrings', 'hipAdductors', 'gastrocnemius', 'gluteusMedius', 'rectusAbdominis', 'obliques'],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/DBSingleLegSplitSquat'],
  },
  {
    id: 'walkingLunge',
    slug: 'walking-lunge',
    equipmentIds: ['bodyweight', 'barbell', 'dumbbell'],
    primaryMuscleIds: ['quadriceps', 'gluteusMaximus'],
    secondaryMuscleIds: ['hamstrings', 'hipAdductors', 'gastrocnemius', 'gluteusMedius', 'rectusAbdominis', 'obliques'],
    movementPattern: 'legs',
    measurementType: 'weightDistance',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/DBWalkingLunge'],
  },
  {
    id: 'legExtension',
    slug: 'leg-extension',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['quadriceps'],
    secondaryMuscleIds: [],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LVLegExtension'],
  },
  {
    id: 'legCurl',
    slug: 'leg-curl',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['hamstrings'],
    secondaryMuscleIds: ['gastrocnemius'],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Hamstrings/LVLyingLegCurl'],
  },
  {
    id: 'standingCalfRaise',
    slug: 'standing-calf-raise',
    equipmentIds: ['machine', 'bodyweight'],
    primaryMuscleIds: ['gastrocnemius'],
    secondaryMuscleIds: ['soleus'],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Gastrocnemius/LVStandingCalfRaise'],
  },
  {
    id: 'seatedCalfRaise',
    slug: 'seated-calf-raise',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['soleus'],
    secondaryMuscleIds: ['gastrocnemius'],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Soleus/LVSeatedCalfRaise'],
  },
  {
    id: 'hipAbduction',
    slug: 'hip-abduction',
    equipmentIds: ['machine', 'resistanceBand'],
    primaryMuscleIds: ['gluteusMedius'],
    secondaryMuscleIds: ['gluteusMaximus'],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/HipAbductor/LVSeatedHipAbduction'],
  },
  {
    id: 'hipAdduction',
    slug: 'hip-adduction',
    equipmentIds: ['machine'],
    primaryMuscleIds: ['hipAdductors'],
    secondaryMuscleIds: [],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/HipAdductors/LVSeatedHipAdduction'],
  },
  {
    id: 'barbellOverheadPress',
    slug: 'barbell-overhead-press',
    equipmentIds: ['barbell', 'rack'],
    primaryMuscleIds: ['deltoidAnterior'],
    secondaryMuscleIds: ['deltoidLateral', 'tricepsBrachii', 'trapezius', 'serratusAnterior', 'pectoralisMajor'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/BBMilitaryPress'],
  },
  {
    id: 'dumbbellShoulderPress',
    slug: 'dumbbell-shoulder-press',
    equipmentIds: ['dumbbell', 'bench'],
    primaryMuscleIds: ['deltoidAnterior'],
    secondaryMuscleIds: ['deltoidLateral', 'tricepsBrachii', 'trapezius', 'serratusAnterior', 'pectoralisMajor'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/DBShoulderPress'],
  },
  {
    id: 'arnoldPress',
    slug: 'arnold-press',
    equipmentIds: ['dumbbell', 'bench'],
    primaryMuscleIds: ['deltoidAnterior'],
    secondaryMuscleIds: ['deltoidLateral', 'tricepsBrachii', 'trapezius', 'serratusAnterior', 'pectoralisMajor'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/DBArnoldPress'],
  },
  {
    id: 'dumbbellLateralRaise',
    slug: 'dumbbell-lateral-raise',
    equipmentIds: ['dumbbell', 'cableMachine'],
    primaryMuscleIds: ['deltoidLateral'],
    secondaryMuscleIds: ['deltoidAnterior', 'trapezius', 'serratusAnterior'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidLateral/DBLateralRaise'],
  },
  {
    id: 'dumbbellFrontRaise',
    slug: 'dumbbell-front-raise',
    equipmentIds: ['dumbbell'],
    primaryMuscleIds: ['deltoidAnterior'],
    secondaryMuscleIds: ['deltoidLateral', 'serratusAnterior', 'trapezius'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/DBFrontRaise'],
  },
  {
    id: 'facePull',
    slug: 'face-pull',
    equipmentIds: ['cableMachine', 'resistanceBand'],
    primaryMuscleIds: ['deltoidPosterior'],
    secondaryMuscleIds: ['rhomboids', 'trapezius', 'brachialis', 'brachioradialis', 'bicepsBrachii'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: [
      'https://exrx.net/WeightExercises/DeltoidPosterior/CBRearDeltRow',
      'https://www.healthline.com/health/face-pulls',
    ],
  },
  {
    id: 'reverseFly',
    slug: 'reverse-fly',
    equipmentIds: ['dumbbell', 'machine', 'cableMachine'],
    primaryMuscleIds: ['deltoidPosterior'],
    secondaryMuscleIds: ['rhomboids', 'trapezius'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidPosterior/DBRearLateralRaise'],
  },
  {
    id: 'shrug',
    slug: 'shrug',
    equipmentIds: ['barbell', 'dumbbell', 'machine'],
    primaryMuscleIds: ['trapezius'],
    secondaryMuscleIds: ['levatorScapulae'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/TrapeziusUpper/BBShrug'],
  },
  {
    id: 'barbellCurl',
    slug: 'barbell-curl',
    equipmentIds: ['barbell'],
    primaryMuscleIds: ['bicepsBrachii'],
    secondaryMuscleIds: ['brachialis', 'brachioradialis'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Biceps/BBCurl'],
  },
  {
    id: 'dumbbellCurl',
    slug: 'dumbbell-curl',
    equipmentIds: ['dumbbell'],
    primaryMuscleIds: ['bicepsBrachii'],
    secondaryMuscleIds: ['brachialis', 'brachioradialis'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Biceps/DBCurl'],
  },
  {
    id: 'hammerCurl',
    slug: 'hammer-curl',
    equipmentIds: ['dumbbell'],
    primaryMuscleIds: ['brachioradialis'],
    secondaryMuscleIds: ['brachialis', 'bicepsBrachii'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Brachioradialis/DBHammerCurl'],
  },
  {
    id: 'preacherCurl',
    slug: 'preacher-curl',
    equipmentIds: ['barbell', 'dumbbell', 'bench'],
    primaryMuscleIds: ['bicepsBrachii'],
    secondaryMuscleIds: ['brachialis', 'brachioradialis'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Biceps/BBPreacherCurl'],
  },
  {
    id: 'concentrationCurl',
    slug: 'concentration-curl',
    equipmentIds: ['dumbbell'],
    primaryMuscleIds: ['bicepsBrachii'],
    secondaryMuscleIds: ['brachialis', 'brachioradialis'],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Biceps/DBConcentrationCurl'],
  },
  {
    id: 'tricepsPushdown',
    slug: 'triceps-pushdown',
    equipmentIds: ['cableMachine'],
    primaryMuscleIds: ['tricepsBrachii'],
    secondaryMuscleIds: ['latissimusDorsi', 'rectusAbdominis', 'obliques'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/CBPushdown'],
  },
  {
    id: 'closeGripBenchPress',
    slug: 'close-grip-bench-press',
    equipmentIds: ['barbell', 'bench', 'rack'],
    primaryMuscleIds: ['tricepsBrachii'],
    secondaryMuscleIds: ['pectoralisMajor', 'deltoidAnterior'],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/BBCloseGripBenchPress'],
  },
  {
    id: 'overheadTricepsExtension',
    slug: 'overhead-triceps-extension',
    equipmentIds: ['dumbbell', 'cableMachine'],
    primaryMuscleIds: ['tricepsBrachii'],
    secondaryMuscleIds: [],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/DBTriExt'],
  },
  {
    id: 'skullCrusher',
    slug: 'skull-crusher',
    equipmentIds: ['barbell', 'dumbbell', 'bench'],
    primaryMuscleIds: ['tricepsBrachii'],
    secondaryMuscleIds: [],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/BBLyingTriExt'],
  },
  {
    id: 'tricepsRopeExtension',
    slug: 'triceps-rope-extension',
    equipmentIds: ['cableMachine'],
    primaryMuscleIds: ['tricepsBrachii'],
    secondaryMuscleIds: [],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/CBPushdown'],
  },
  {
    id: 'crunch',
    slug: 'crunch',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['rectusAbdominis'],
    secondaryMuscleIds: ['obliques'],
    movementPattern: 'core',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/BWCrunch'],
  },
  {
    id: 'plank',
    slug: 'plank',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['rectusAbdominis', 'transverseAbdominis', 'obliques'],
    secondaryMuscleIds: ['deltoidAnterior', 'trapezius', 'erectorSpinae'],
    movementPattern: 'core',
    measurementType: 'duration',
    sourceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/BWFrontPlank'],
  },
  {
    id: 'hangingLegRaise',
    slug: 'hanging-leg-raise',
    equipmentIds: ['bodyweight', 'pullUpBar'],
    primaryMuscleIds: ['rectusAbdominis', 'iliopsoas'],
    secondaryMuscleIds: ['obliques', 'quadriceps'],
    movementPattern: 'core',
    measurementType: 'reps',
    sourceUrls: [
      'https://exrx.net/WeightExercises/RectusAbdominis/BWHangingLegHipRaiseAbStrap',
      'https://exrx.net/WeightExercises/HipFlexors/WtHangLegRaise',
    ],
  },
  {
    id: 'russianTwist',
    slug: 'russian-twist',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['obliques'],
    secondaryMuscleIds: ['rectusAbdominis', 'iliopsoas'],
    movementPattern: 'core',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/Obliques/WtRussianTwist'],
  },
  {
    id: 'sitUp',
    slug: 'sit-up',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['rectusAbdominis'],
    secondaryMuscleIds: ['obliques', 'iliopsoas'],
    movementPattern: 'core',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/BWSitUp'],
  },
  {
    id: 'cableCrunch',
    slug: 'cable-crunch',
    equipmentIds: ['cableMachine'],
    primaryMuscleIds: ['rectusAbdominis'],
    secondaryMuscleIds: ['obliques'],
    movementPattern: 'core',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/CBKneelingCrunch'],
  },
  {
    id: 'deadBug',
    slug: 'dead-bug',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['transverseAbdominis'],
    secondaryMuscleIds: ['rectusAbdominis', 'obliques', 'iliopsoas'],
    movementPattern: 'core',
    measurementType: 'reps',
    sourceUrls: [],
  },
  {
    id: 'birdDog',
    slug: 'bird-dog',
    equipmentIds: ['bodyweight'],
    primaryMuscleIds: ['transverseAbdominis', 'rectusAbdominis'],
    secondaryMuscleIds: ['erectorSpinae', 'gluteusMaximus', 'obliques', 'deltoidPosterior'],
    movementPattern: 'core',
    measurementType: 'reps',
    sourceUrls: [],
  },
]
