import type { Exercise } from './types'

export const exercises: Exercise[] = [
  {
    id: 'barbellBenchPress',
    slug: 'barbell-bench-press',
    muscleDistribution: [
      { muscleGroupId: 'chest', ratio: 0.6 },
      { muscleGroupId: 'shoulders', ratio: 0.2 },
      { muscleGroupId: 'arms', ratio: 0.2 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/BBBenchPress'],
  },
  {
    id: 'dumbbellBenchPress',
    slug: 'dumbbell-bench-press',
    muscleDistribution: [
      { muscleGroupId: 'chest', ratio: 0.6 },
      { muscleGroupId: 'shoulders', ratio: 0.2 },
      { muscleGroupId: 'arms', ratio: 0.2 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/DBBenchPress'],
  },
  {
    id: 'inclineBarbellBenchPress',
    slug: 'incline-barbell-bench-press',
    muscleDistribution: [
      { muscleGroupId: 'chest', ratio: 0.55 },
      { muscleGroupId: 'shoulders', ratio: 0.25 },
      { muscleGroupId: 'arms', ratio: 0.2 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralClavicular/BBInclineBenchPress'],
  },
  {
    id: 'inclineDumbbellBenchPress',
    slug: 'incline-dumbbell-bench-press',
    muscleDistribution: [
      { muscleGroupId: 'chest', ratio: 0.55 },
      { muscleGroupId: 'shoulders', ratio: 0.25 },
      { muscleGroupId: 'arms', ratio: 0.2 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralClavicular/DBInclineBenchPress'],
  },
  {
    id: 'declineBarbellBenchPress',
    slug: 'decline-barbell-bench-press',
    muscleDistribution: [
      { muscleGroupId: 'chest', ratio: 0.65 },
      { muscleGroupId: 'arms', ratio: 0.2 },
      { muscleGroupId: 'shoulders', ratio: 0.15 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/BBDeclineBenchPress'],
  },
  {
    id: 'declineDumbbellBenchPress',
    slug: 'decline-dumbbell-bench-press',
    muscleDistribution: [
      { muscleGroupId: 'chest', ratio: 0.65 },
      { muscleGroupId: 'arms', ratio: 0.2 },
      { muscleGroupId: 'shoulders', ratio: 0.15 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/DBDeclineBenchPress'],
  },
  {
    id: 'pecDeck',
    slug: 'pec-deck',
    muscleDistribution: [
      { muscleGroupId: 'chest', ratio: 0.85 },
      { muscleGroupId: 'arms', ratio: 0.15 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/LVPecDeckFly'],
  },
  {
    id: 'cableFly',
    slug: 'cable-fly',
    muscleDistribution: [
      { muscleGroupId: 'chest', ratio: 0.85 },
      { muscleGroupId: 'arms', ratio: 0.15 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/CBStandingFly'],
  },
  {
    id: 'dip',
    slug: 'dip',
    muscleDistribution: [
      { muscleGroupId: 'chest', ratio: 0.5 },
      { muscleGroupId: 'arms', ratio: 0.35 },
      { muscleGroupId: 'shoulders', ratio: 0.15 },
    ],
    movementPattern: 'push',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/BWChestDip'],
  },
  {
    id: 'pushUp',
    slug: 'push-up',
    muscleDistribution: [
      { muscleGroupId: 'chest', ratio: 0.5 },
      { muscleGroupId: 'shoulders', ratio: 0.2 },
      { muscleGroupId: 'arms', ratio: 0.2 },
      { muscleGroupId: 'core', ratio: 0.1 },
    ],
    movementPattern: 'push',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/BWPushup'],
  },
  {
    id: 'weightedPushUp',
    slug: 'weighted-push-up',
    muscleDistribution: [
      { muscleGroupId: 'chest', ratio: 0.5 },
      { muscleGroupId: 'shoulders', ratio: 0.2 },
      { muscleGroupId: 'arms', ratio: 0.2 },
      { muscleGroupId: 'core', ratio: 0.1 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/PectoralSternal/WtPushup'],
  },
  {
    id: 'pullUp',
    slug: 'pull-up',
    muscleDistribution: [
      { muscleGroupId: 'back', ratio: 0.65 },
      { muscleGroupId: 'arms', ratio: 0.25 },
      { muscleGroupId: 'shoulders', ratio: 0.1 },
    ],
    movementPattern: 'pull',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/WtPullup'],
  },
  {
    id: 'wideGripPullUp',
    slug: 'wide-grip-pull-up',
    muscleDistribution: [
      { muscleGroupId: 'back', ratio: 0.7 },
      { muscleGroupId: 'arms', ratio: 0.2 },
      { muscleGroupId: 'shoulders', ratio: 0.1 },
    ],
    movementPattern: 'pull',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/WtPullup'],
  },
  {
    id: 'chinUp',
    slug: 'chin-up',
    muscleDistribution: [
      { muscleGroupId: 'back', ratio: 0.55 },
      { muscleGroupId: 'arms', ratio: 0.35 },
      { muscleGroupId: 'shoulders', ratio: 0.1 },
    ],
    movementPattern: 'pull',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/WtUnderhandChinup'],
  },
  {
    id: 'latPulldown',
    slug: 'lat-pulldown',
    muscleDistribution: [
      { muscleGroupId: 'back', ratio: 0.65 },
      { muscleGroupId: 'arms', ratio: 0.25 },
      { muscleGroupId: 'shoulders', ratio: 0.1 },
    ],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/CBFrontPulldown'],
  },
  {
    id: 'closeGripLatPulldown',
    slug: 'close-grip-lat-pulldown',
    muscleDistribution: [
      { muscleGroupId: 'back', ratio: 0.6 },
      { muscleGroupId: 'arms', ratio: 0.3 },
      { muscleGroupId: 'shoulders', ratio: 0.1 },
    ],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/CBCloseGripPulldown'],
  },
  {
    id: 'barbellRow',
    slug: 'barbell-row',
    muscleDistribution: [
      { muscleGroupId: 'back', ratio: 0.6 },
      { muscleGroupId: 'arms', ratio: 0.15 },
      { muscleGroupId: 'shoulders', ratio: 0.15 },
      { muscleGroupId: 'legs', ratio: 0.1 },
    ],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/BackGeneral/BBBentOverRow'],
  },
  {
    id: 'seatedRow',
    slug: 'seated-row',
    muscleDistribution: [
      { muscleGroupId: 'back', ratio: 0.65 },
      { muscleGroupId: 'arms', ratio: 0.2 },
      { muscleGroupId: 'shoulders', ratio: 0.15 },
    ],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/BackGeneral/CBSeatedRow'],
  },
  {
    id: 'singleArmDumbbellRow',
    slug: 'single-arm-dumbbell-row',
    muscleDistribution: [
      { muscleGroupId: 'back', ratio: 0.6 },
      { muscleGroupId: 'arms', ratio: 0.2 },
      { muscleGroupId: 'shoulders', ratio: 0.1 },
      { muscleGroupId: 'core', ratio: 0.1 },
    ],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/BackGeneral/DBBentOverRow'],
  },
  {
    id: 'tBarRow',
    slug: 't-bar-row',
    muscleDistribution: [
      { muscleGroupId: 'back', ratio: 0.65 },
      { muscleGroupId: 'arms', ratio: 0.2 },
      { muscleGroupId: 'shoulders', ratio: 0.15 },
    ],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/BackGeneral/LVTBarRow'],
  },
  {
    id: 'straightArmPulldown',
    slug: 'straight-arm-pulldown',
    muscleDistribution: [
      { muscleGroupId: 'back', ratio: 0.75 },
      { muscleGroupId: 'arms', ratio: 0.15 },
      { muscleGroupId: 'chest', ratio: 0.1 },
    ],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/LatissimusDorsi/CBStraightArmPulldown'],
  },
  {
    id: 'deadlift',
    slug: 'deadlift',
    muscleDistribution: [
      { muscleGroupId: 'legs', ratio: 0.5 },
      { muscleGroupId: 'back', ratio: 0.35 },
      { muscleGroupId: 'core', ratio: 0.15 },
    ],
    movementPattern: 'fullBody',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/ErectorSpinae/BBDeadlift'],
  },
  {
    id: 'romanianDeadlift',
    slug: 'romanian-deadlift',
    muscleDistribution: [
      { muscleGroupId: 'legs', ratio: 0.55 },
      { muscleGroupId: 'back', ratio: 0.3 },
      { muscleGroupId: 'core', ratio: 0.15 },
    ],
    movementPattern: 'fullBody',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/OlympicLifts/RomanianDeadlift'],
  },
  {
    id: 'sumoDeadlift',
    slug: 'sumo-deadlift',
    muscleDistribution: [
      { muscleGroupId: 'legs', ratio: 0.6 },
      { muscleGroupId: 'back', ratio: 0.25 },
      { muscleGroupId: 'core', ratio: 0.15 },
    ],
    movementPattern: 'fullBody',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/ErectorSpinae/BBSumoDeadlift'],
  },
  {
    id: 'barbellSquat',
    slug: 'barbell-squat',
    muscleDistribution: [
      { muscleGroupId: 'legs', ratio: 0.75 },
      { muscleGroupId: 'core', ratio: 0.15 },
      { muscleGroupId: 'back', ratio: 0.1 },
    ],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BBSquat'],
  },
  {
    id: 'squat',
    slug: 'squat',
    muscleDistribution: [
      { muscleGroupId: 'legs', ratio: 0.75 },
      { muscleGroupId: 'core', ratio: 0.15 },
      { muscleGroupId: 'back', ratio: 0.1 },
    ],
    movementPattern: 'legs',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BWSquat'],
  },
  {
    id: 'frontSquat',
    slug: 'front-squat',
    muscleDistribution: [
      { muscleGroupId: 'legs', ratio: 0.75 },
      { muscleGroupId: 'core', ratio: 0.15 },
      { muscleGroupId: 'back', ratio: 0.1 },
    ],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BBFrontSquat'],
  },
  {
    id: 'legPress',
    slug: 'leg-press',
    muscleDistribution: [{ muscleGroupId: 'legs', ratio: 1 }],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LV45LegPress'],
  },
  {
    id: 'legPressMachine',
    slug: 'leg-press-machine',
    muscleDistribution: [{ muscleGroupId: 'legs', ratio: 1 }],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LV45LegPress'],
  },
  {
    id: 'hackSquat',
    slug: 'hack-squat',
    muscleDistribution: [{ muscleGroupId: 'legs', ratio: 1 }],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LVHackSquat'],
  },
  {
    id: 'gluteBridge',
    slug: 'glute-bridge',
    muscleDistribution: [
      { muscleGroupId: 'legs', ratio: 0.8 },
      { muscleGroupId: 'core', ratio: 0.2 },
    ],
    movementPattern: 'legs',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/GluteusMaximus/BWGluteBridge'],
  },
  {
    id: 'barbellHipThrust',
    slug: 'barbell-hip-thrust',
    muscleDistribution: [
      { muscleGroupId: 'legs', ratio: 0.75 },
      { muscleGroupId: 'core', ratio: 0.15 },
      { muscleGroupId: 'back', ratio: 0.1 },
    ],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/GluteusMaximus/BBHipThrust'],
  },
  {
    id: 'lunge',
    slug: 'lunge',
    muscleDistribution: [
      { muscleGroupId: 'legs', ratio: 0.8 },
      { muscleGroupId: 'core', ratio: 0.2 },
    ],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/BBLunge'],
  },
  {
    id: 'bulgarianSplitSquat',
    slug: 'bulgarian-split-squat',
    muscleDistribution: [
      { muscleGroupId: 'legs', ratio: 0.8 },
      { muscleGroupId: 'core', ratio: 0.2 },
    ],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/DBSingleLegSplitSquat'],
  },
  {
    id: 'walkingLunge',
    slug: 'walking-lunge',
    muscleDistribution: [
      { muscleGroupId: 'legs', ratio: 0.8 },
      { muscleGroupId: 'core', ratio: 0.2 },
    ],
    movementPattern: 'legs',
    measurementType: 'weightDistance',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/DBWalkingLunge'],
  },
  {
    id: 'legExtension',
    slug: 'leg-extension',
    muscleDistribution: [{ muscleGroupId: 'legs', ratio: 1 }],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Quadriceps/LVLegExtension'],
  },
  {
    id: 'legCurl',
    slug: 'leg-curl',
    muscleDistribution: [{ muscleGroupId: 'legs', ratio: 1 }],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Hamstrings/LVLyingLegCurl'],
  },
  {
    id: 'standingCalfRaise',
    slug: 'standing-calf-raise',
    muscleDistribution: [{ muscleGroupId: 'legs', ratio: 1 }],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Gastrocnemius/LVStandingCalfRaise'],
  },
  {
    id: 'seatedCalfRaise',
    slug: 'seated-calf-raise',
    muscleDistribution: [{ muscleGroupId: 'legs', ratio: 1 }],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Soleus/LVSeatedCalfRaise'],
  },
  {
    id: 'hipAbduction',
    slug: 'hip-abduction',
    muscleDistribution: [{ muscleGroupId: 'legs', ratio: 1 }],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/HipAbductor/LVSeatedHipAbduction'],
  },
  {
    id: 'hipAdduction',
    slug: 'hip-adduction',
    muscleDistribution: [{ muscleGroupId: 'legs', ratio: 1 }],
    movementPattern: 'legs',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/HipAdductors/LVSeatedHipAdduction'],
  },
  {
    id: 'barbellOverheadPress',
    slug: 'barbell-overhead-press',
    muscleDistribution: [
      { muscleGroupId: 'shoulders', ratio: 0.6 },
      { muscleGroupId: 'arms', ratio: 0.25 },
      { muscleGroupId: 'chest', ratio: 0.1 },
      { muscleGroupId: 'back', ratio: 0.05 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/BBMilitaryPress'],
  },
  {
    id: 'dumbbellShoulderPress',
    slug: 'dumbbell-shoulder-press',
    muscleDistribution: [
      { muscleGroupId: 'shoulders', ratio: 0.6 },
      { muscleGroupId: 'arms', ratio: 0.25 },
      { muscleGroupId: 'chest', ratio: 0.1 },
      { muscleGroupId: 'back', ratio: 0.05 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/DBShoulderPress'],
  },
  {
    id: 'arnoldPress',
    slug: 'arnold-press',
    muscleDistribution: [
      { muscleGroupId: 'shoulders', ratio: 0.6 },
      { muscleGroupId: 'arms', ratio: 0.25 },
      { muscleGroupId: 'chest', ratio: 0.1 },
      { muscleGroupId: 'back', ratio: 0.05 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/DBArnoldPress'],
  },
  {
    id: 'dumbbellLateralRaise',
    slug: 'dumbbell-lateral-raise',
    muscleDistribution: [
      { muscleGroupId: 'shoulders', ratio: 0.85 },
      { muscleGroupId: 'back', ratio: 0.1 },
      { muscleGroupId: 'chest', ratio: 0.05 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidLateral/DBLateralRaise'],
  },
  {
    id: 'dumbbellFrontRaise',
    slug: 'dumbbell-front-raise',
    muscleDistribution: [
      { muscleGroupId: 'shoulders', ratio: 0.85 },
      { muscleGroupId: 'chest', ratio: 0.1 },
      { muscleGroupId: 'back', ratio: 0.05 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidAnterior/DBFrontRaise'],
  },
  {
    id: 'facePull',
    slug: 'face-pull',
    muscleDistribution: [
      { muscleGroupId: 'shoulders', ratio: 0.6 },
      { muscleGroupId: 'back', ratio: 0.25 },
      { muscleGroupId: 'arms', ratio: 0.15 },
    ],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: [
      'https://exrx.net/WeightExercises/DeltoidPosterior/CBRearDeltRow',
      'https://www.healthline.com/health/face-pulls',
    ],
  },
  {
    id: 'reverseFly',
    slug: 'reverse-fly',
    muscleDistribution: [
      { muscleGroupId: 'shoulders', ratio: 0.7 },
      { muscleGroupId: 'back', ratio: 0.3 },
    ],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/DeltoidPosterior/DBRearLateralRaise'],
  },
  {
    id: 'shrug',
    slug: 'shrug',
    muscleDistribution: [{ muscleGroupId: 'back', ratio: 1 }],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/TrapeziusUpper/BBShrug'],
  },
  {
    id: 'barbellCurl',
    slug: 'barbell-curl',
    muscleDistribution: [{ muscleGroupId: 'arms', ratio: 1 }],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Biceps/BBCurl'],
  },
  {
    id: 'dumbbellCurl',
    slug: 'dumbbell-curl',
    muscleDistribution: [{ muscleGroupId: 'arms', ratio: 1 }],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Biceps/DBCurl'],
  },
  {
    id: 'hammerCurl',
    slug: 'hammer-curl',
    muscleDistribution: [{ muscleGroupId: 'arms', ratio: 1 }],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Brachioradialis/DBHammerCurl'],
  },
  {
    id: 'preacherCurl',
    slug: 'preacher-curl',
    muscleDistribution: [{ muscleGroupId: 'arms', ratio: 1 }],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Biceps/BBPreacherCurl'],
  },
  {
    id: 'concentrationCurl',
    slug: 'concentration-curl',
    muscleDistribution: [{ muscleGroupId: 'arms', ratio: 1 }],
    movementPattern: 'pull',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Biceps/DBConcentrationCurl'],
  },
  {
    id: 'tricepsPushdown',
    slug: 'triceps-pushdown',
    muscleDistribution: [
      { muscleGroupId: 'arms', ratio: 0.9 },
      { muscleGroupId: 'back', ratio: 0.05 },
      { muscleGroupId: 'core', ratio: 0.05 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/CBPushdown'],
  },
  {
    id: 'closeGripBenchPress',
    slug: 'close-grip-bench-press',
    muscleDistribution: [
      { muscleGroupId: 'arms', ratio: 0.6 },
      { muscleGroupId: 'chest', ratio: 0.25 },
      { muscleGroupId: 'shoulders', ratio: 0.15 },
    ],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/BBCloseGripBenchPress'],
  },
  {
    id: 'overheadTricepsExtension',
    slug: 'overhead-triceps-extension',
    muscleDistribution: [{ muscleGroupId: 'arms', ratio: 1 }],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/DBTriExt'],
  },
  {
    id: 'skullCrusher',
    slug: 'skull-crusher',
    muscleDistribution: [{ muscleGroupId: 'arms', ratio: 1 }],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/BBLyingTriExt'],
  },
  {
    id: 'tricepsRopeExtension',
    slug: 'triceps-rope-extension',
    muscleDistribution: [{ muscleGroupId: 'arms', ratio: 1 }],
    movementPattern: 'push',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/Triceps/CBPushdown'],
  },
  {
    id: 'crunch',
    slug: 'crunch',
    muscleDistribution: [{ muscleGroupId: 'core', ratio: 1 }],
    movementPattern: 'core',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/BWCrunch'],
  },
  {
    id: 'plank',
    slug: 'plank',
    muscleDistribution: [
      { muscleGroupId: 'core', ratio: 0.75 },
      { muscleGroupId: 'shoulders', ratio: 0.15 },
      { muscleGroupId: 'back', ratio: 0.1 },
    ],
    movementPattern: 'core',
    measurementType: 'duration',
    sourceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/BWFrontPlank'],
  },
  {
    id: 'hangingLegRaise',
    slug: 'hanging-leg-raise',
    muscleDistribution: [
      { muscleGroupId: 'core', ratio: 0.7 },
      { muscleGroupId: 'legs', ratio: 0.3 },
    ],
    movementPattern: 'core',
    measurementType: 'reps',
    sourceUrls: [
      'https://exrx.net/WeightExercises/RectusAbdominis/BWHangingLegHipRaiseAbStrap',
      'https://exrx.net/WeightExercises/HipFlexors/WtHangLegRaise',
    ],
  },
  {
    id: 'russianTwist',
    slug: 'russian-twist',
    muscleDistribution: [
      { muscleGroupId: 'core', ratio: 0.8 },
      { muscleGroupId: 'legs', ratio: 0.2 },
    ],
    movementPattern: 'core',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/Obliques/WtRussianTwist'],
  },
  {
    id: 'sitUp',
    slug: 'sit-up',
    muscleDistribution: [
      { muscleGroupId: 'core', ratio: 0.8 },
      { muscleGroupId: 'legs', ratio: 0.2 },
    ],
    movementPattern: 'core',
    measurementType: 'reps',
    sourceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/BWSitUp'],
  },
  {
    id: 'cableCrunch',
    slug: 'cable-crunch',
    muscleDistribution: [{ muscleGroupId: 'core', ratio: 1 }],
    movementPattern: 'core',
    measurementType: 'weightReps',
    sourceUrls: ['https://exrx.net/WeightExercises/RectusAbdominis/CBKneelingCrunch'],
  },
  {
    id: 'deadBug',
    slug: 'dead-bug',
    muscleDistribution: [
      { muscleGroupId: 'core', ratio: 0.8 },
      { muscleGroupId: 'legs', ratio: 0.2 },
    ],
    movementPattern: 'core',
    measurementType: 'reps',
    sourceUrls: [],
  },
  {
    id: 'birdDog',
    slug: 'bird-dog',
    muscleDistribution: [
      { muscleGroupId: 'core', ratio: 0.55 },
      { muscleGroupId: 'back', ratio: 0.2 },
      { muscleGroupId: 'legs', ratio: 0.15 },
      { muscleGroupId: 'shoulders', ratio: 0.1 },
    ],
    movementPattern: 'core',
    measurementType: 'reps',
    sourceUrls: [],
  },
]
