import type { Muscle } from './types'

export const muscles: Muscle[] = [
  { id: 'pectoralisMajor', groupId: 'chest' },
  { id: 'pectoralisMinor', groupId: 'chest' },
  { id: 'serratusAnterior', groupId: 'chest' },
  { id: 'latissimusDorsi', groupId: 'back' },
  { id: 'trapezius', groupId: 'back' },
  { id: 'levatorScapulae', groupId: 'back' },
  { id: 'rhomboids', groupId: 'back' },
  { id: 'erectorSpinae', groupId: 'back' },
  { id: 'deltoidAnterior', groupId: 'shoulders' },
  { id: 'deltoidLateral', groupId: 'shoulders' },
  { id: 'deltoidPosterior', groupId: 'shoulders' },
  { id: 'bicepsBrachii', groupId: 'arms' },
  { id: 'brachialis', groupId: 'arms' },
  { id: 'brachioradialis', groupId: 'arms' },
  { id: 'tricepsBrachii', groupId: 'arms' },
  { id: 'rectusAbdominis', groupId: 'core' },
  { id: 'obliques', groupId: 'core' },
  { id: 'transverseAbdominis', groupId: 'core' },
  { id: 'iliopsoas', groupId: 'legs' },
  { id: 'gluteusMaximus', groupId: 'legs' },
  { id: 'gluteusMedius', groupId: 'legs' },
  { id: 'hipAdductors', groupId: 'legs' },
  { id: 'quadriceps', groupId: 'legs' },
  { id: 'hamstrings', groupId: 'legs' },
  { id: 'gastrocnemius', groupId: 'legs' },
  { id: 'soleus', groupId: 'legs' },
]
