import type { Muscle } from './types'

export const muscles: Muscle[] = [
  { id: 'pectoralisMajor', groupId: 'chest', aliases: ['pecs', 'chest'] },
  { id: 'pectoralisMinor', groupId: 'chest', aliases: ['pec minor'] },
  { id: 'serratusAnterior', groupId: 'chest', aliases: ['serratus'] },
  { id: 'latissimusDorsi', groupId: 'back', aliases: ['lats'] },
  { id: 'trapezius', groupId: 'back', aliases: ['traps'] },
  { id: 'levatorScapulae', groupId: 'back', aliases: ['levator scapula'] },
  { id: 'rhomboids', groupId: 'back', aliases: ['rhomboid major', 'rhomboid minor'] },
  { id: 'erectorSpinae', groupId: 'back', aliases: ['spinal erectors', 'lower back'] },
  { id: 'deltoidAnterior', groupId: 'shoulders', aliases: ['front delt', 'anterior deltoid'] },
  { id: 'deltoidLateral', groupId: 'shoulders', aliases: ['side delt', 'lateral deltoid', 'middle delt'] },
  { id: 'deltoidPosterior', groupId: 'shoulders', aliases: ['rear delt', 'posterior deltoid'] },
  { id: 'bicepsBrachii', groupId: 'arms', aliases: ['biceps'] },
  { id: 'brachialis', groupId: 'arms', aliases: ['brachialis'] },
  { id: 'brachioradialis', groupId: 'arms', aliases: ['forearm flexor'] },
  { id: 'tricepsBrachii', groupId: 'arms', aliases: ['triceps'] },
  { id: 'rectusAbdominis', groupId: 'core', aliases: ['abs', 'six pack'] },
  { id: 'obliques', groupId: 'core', aliases: ['internal obliques', 'external obliques'] },
  { id: 'transverseAbdominis', groupId: 'core', aliases: ['deep abs', 'transversus abdominis'] },
  { id: 'iliopsoas', groupId: 'hips', aliases: ['hip flexors'] },
  { id: 'gluteusMaximus', groupId: 'hips', aliases: ['glutes', 'glute max'] },
  { id: 'gluteusMedius', groupId: 'hips', aliases: ['glute med', 'hip abductors'] },
  { id: 'hipAdductors', groupId: 'hips', aliases: ['adductors', 'inner thigh'] },
  { id: 'quadriceps', groupId: 'quadriceps', aliases: ['quads'] },
  { id: 'hamstrings', groupId: 'hamstrings', aliases: ['hamstrings'] },
  { id: 'gastrocnemius', groupId: 'calves', aliases: ['gastroc', 'calf'] },
  { id: 'soleus', groupId: 'calves', aliases: ['soleus'] },
]
